# column widths
DATE_SIZE   : 12
TRANS_SIZE  : 8
CAT_SIZE    : 15
DESC_SIZE   : 47
AMOUNT_SIZE : 12
NUM_SIZE    : 6
USER_SIZE   : 7

# display separators
HLINE_CHAR : '='
VLINE_CHAR : '|'
TRANS_FILL_CHAR : '*'
REPORT_HEADER_FILL_CHAR : "*"

# categories for selection
DEBIT_CATEGORIES  : ["Groceries", "Gas", "Bills", "Entertainment", "Food", "Savings", "Good Time","Vacation","Christmas", "Wedding", "Medical","Whiskey", "Other"]
CREDIT_CATEGORIES : ["Bills", "Other", "Paycheck"]
USERS : ["Share", "Mine"]
USE_GUI : False

DATE_FORMAT  : "%m/%d/%Y" # format date must be entered in (default : %m/%d/%Y -> m/d/yyyy)
THOUSAND_SEP : True # use the thousand separator for the amount
USE_SQL      : False # use sqlite instead of xml
FILE_NAME    : "2022.xml" # default file to load
DB_NAME      : "checkbook.db" # default sql database to load
SORT_BY_KEY  : "Date" # default key to sort by when none is entered
REPORT_DISPLAY_0 : False # display zero values in report
REPORT_0_FILL_CHAR : "" # character to display in place of the zero when REPORT_DISPLAY_0 is false (can be blank)
DEFAULT_COPY_TO : "to.xml" # default file to copy to
DEFAULT_TO_CSV: "checkbook.csv"
PATH_FOR_REGISTERS: "./Registers/;./Registers/Test/"
